// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jusmceaydtffxejdzrii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1c21jZWF5ZHRmZnhlamR6cmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMzgzNjAsImV4cCI6MjA3NDgxNDM2MH0.ORt9IsWOL40vk_3AbNfGw4GTSLLCSiq2k4JglwkDDWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});